version: '3.5'

services:

  myweb:
    build:
      context: ./
    image: myweb:v0.1
    environment:
        LANG: 'en_US.UTF-8'
    container_name: myweb
    ports:
      - "80:80"
    volumes:
      - ./log:/var/log
      - ./tmp:/tmp
      - ./myweb:/www
    links:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: myweb-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
